create table public.mail
(
    id                        bigint generated by default as identity
        primary key,
    body                      text,
    content_transfer_encoding varchar(255),
    content_type              varchar(255),
    date                      timestamp(6),
    mime_version              varchar(255),
    recipient                 varchar(255),
    sender                    varchar(255),
    subject                   varchar(255)
);

alter table public.mail
    owner to postgres;

create table public.email_parts
(
    id                        bigint generated by default as identity
        primary key,
    email_id                  bigint
        references public.mail,
    content_type              varchar(255),
    content_transfer_encoding varchar(255),
    body                      text
);

alter table public.email_parts
    owner to postgres;

create table public."user"
(
    id       bigserial
        primary key,
    username varchar(255) not null
        unique,
    password varchar(255) not null
);

alter table public."user"
    owner to postgres;


